export default {
  HOSTED_FIELDS: {
    HOSTED_FIELDS_TOKENIZATION_NETWORK_ERROR:
      'HOSTED_FIELDS_TOKENIZATION_NETWORK_ERROR',
    HOSTED_FIELDS_TOKENIZATION_FAIL_ON_DUPLICATE:
      'HOSTED_FIELDS_TOKENIZATION_FAIL_ON_DUPLICATE',
    HOSTED_FIELDS_TOKENIZATION_CVV_VERIFICATION_FAILED:
      'HOSTED_FIELDS_TOKENIZATION_CVV_VERIFICATION_FAILED',
    HOSTED_FIELDS_FAILED_TOKENIZATION: 'HOSTED_FIELDS_FAILED_TOKENIZATION',
    HOSTED_FIELDS_FIELDS_EMPTY: 'HOSTED_FIELDS_FIELDS_EMPTY',
    HOSTED_FIELDS_FIELDS_INVALID: 'HOSTED_FIELDS_FIELDS_INVALID'
  }
};
